import Head from 'next/head';
import Image from 'next/image';
import { connectToDatabase } from '../lib/mongodb';
import styles from '../styles/Home.module.css';

export default function Home({ res }) {
  const letters = JSON.parse(res).letters;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Letters</h1>
        <h2>You have ({letters.length} letters)</h2>
        {letters.reverse().map((letter) => (
          <>
            <p>{letter.message}</p>
            <p>{new Date(letter.date).toLocaleString()}</p>
          </>
        ))}
      </main>
    </div>
  );
}

export async function getServerSideProps({ params }) {
  const { db } = await connectToDatabase();
  // const counts = JSON.stringify(dbRes);

  const messageRes = [];

  const dbRes = await db.collection('playerLetters').find({}).toArray();
  console.log(dbRes);

  for await (const doc of dbRes) {
    messageRes.push(doc);
  }

  // const countsObj = {};
  // for (const countObj of messageRes) {
  //   if (countObj._id) {
  //     countsObj[countObj._id] = countObj;
  //   }
  // }

  const resString = JSON.stringify({ letters: dbRes });
  // sendMe.forEach();
  return { props: { res: resString } };
}
